# Output config
temp_dir: 'tmp'
out_dir: 'output'
interval_split: 128

# Sun et al pQTL config
sun2018_in_gs_dir: 'gs://genetics-portal-sumstats/molecular_qtl/pqtl/SUN2018'
sun2018_manifest_gs: 'gs://genetics-portal-raw/pqtl_sun2018/raw_data/001_SOMALOGIC_GWAS_protein_info.csv'
sun2018_manifest_local: 'configs/Sun_pQTL_SOMALOGIC_GWAS_protein_info.ensembl.manifest.tsv'
sun2018_cis_window: 1000000 # Window around gene TSS to be called "cis" data
sun2018_cis_pval: 2.5e-5    # P-value threshold for cis data
sun2018_trans_pval: 5e-8    # P-value threshold for cis data

# GTEx v7 eQTL config
gtex7_raw_gs_dir: 'genetics-portal-raw/eqtl_gtex_v7/egenes'
gtex7_manifest: 'configs/GTEx_v7_tissues.manifest.tsv'
